###Recuperar todo los candidatos
GET https://prueba-tecnica-backend-sp.onrender.com/api/candidates

###Crear un candidato
POST https://prueba-tecnica-backend-sp.onrender.com/api/candidates
Content-Type: application/json

{
    "name": "Oscar Meneses Solís",
    "age": 24,
    "email": "meneses.solis.oscar99@gmail.com",
    "phone": "5567039752",
    "interviewDate": "2024-05-01",
    "skills": "JavaScript, HTML, CSS, React, Nodejs, AWS"
}

###Actualizar un candidato
PATCH https://prueba-tecnica-backend-sp.onrender.com/api/candidates/
Content-Type: application/json

{
    "age": 28
}

###Eliminar un candidato
DELETE https://prueba-tecnica-backend-sp.onrender.com/api/candidates/